let trendChart,statusChart,bpChart,vitalDetailChart;let activeVitalTab="bp";
const statusClass=s=>!s?"status-unknown":"status-"+String(s).toLowerCase().replace(/\s+/g,"-");
const statusColor=s=>s==="High"?"#e84c4f":s==="Low"||s==="Overweight"?"#f4a340":s==="Normal"?"#16a06b":"#87928f";
const cellColor=s=>s==="High"?"#ffd8d8":s==="Low"||s==="Overweight"?"#ffe3b8":s==="Normal"?"#ccf4dc":"#eee";
const score=s=>s==="High"||s==="Overweight"?3:s==="Normal"?2:s==="Low"?1:0;
function bpLevel(row){if(row.systolicStatus==="High"||row.diastolicStatus==="High")return"High";if(row.systolicStatus==="Low"||row.diastolicStatus==="Low")return"Low";if(row.systolicStatus==="Normal"&&row.diastolicStatus==="Normal")return"Normal";return row.systolicStatus||row.diastolicStatus||"Unknown"}
function rowPassesSidebarFilters(row){const bpF=bpLevelSelect.value, gF=glucoseLevelSelect.value;return (bpF==="All"||bpLevel(row)===bpF)&&(gF==="All"||row.glucoseStatus===gF)}
function patientsForDoctor(){let rows=READINGS;if(doctorSelect.value&&doctorSelect.value!=="All")rows=rows.filter(d=>d.doctor===doctorSelect.value);rows=rows.filter(rowPassesSidebarFilters);return[...new Set(rows.map(d=>d.patientName))].sort()}
function initFilters(){doctorSelect.innerHTML=["All",...[...new Set(READINGS.map(d=>d.doctor))].sort()].map(x=>`<option>${x}</option>`).join("");bpLevelSelect.innerHTML=["All","High","Normal","Low","Unknown"].map(x=>`<option>${x}</option>`).join("");glucoseLevelSelect.innerHTML=["All","High","Normal","Low","Unknown"].map(x=>`<option>${x}</option>`).join("");refreshPatientOptions();dateSelect.innerHTML=["Latest",...[...new Set(READINGS.map(d=>d.date))].sort()].map(x=>`<option>${x}</option>`).join("")}
function refreshPatientOptions(){const cur=patientSelect.value,p=patientsForDoctor();patientSelect.innerHTML=p.map(x=>`<option>${x}</option>`).join("");if(p.includes(cur))patientSelect.value=cur}
function filteredRows(){let rows=READINGS.filter(d=>d.patientName===patientSelect.value);if(doctorSelect.value!=="All")rows=rows.filter(d=>d.doctor===doctorSelect.value);if(dateSelect.value!=="Latest")rows=rows.filter(d=>d.date===dateSelect.value);rows=rows.filter(rowPassesSidebarFilters);return rows.sort((a,b)=>new Date(a.dateTime)-new Date(b.dateTime))}
function latestRow(){const r=filteredRows();return r[r.length-1]||{}}
function setCard(id,valId,statId,val,st){document.getElementById(id).className="card status-card "+statusClass(st);document.getElementById(valId).textContent=val??"--";document.getElementById(statId).textContent=st??"Unknown"}
function updateCards(){const r=latestRow(),bp=r.systolic?`${Math.round(r.systolic)}/${Math.round(r.diastolic)}`:"--",bps=bpLevel(r);setCard("glucoseCard","glucoseValue","glucoseStatus",r.glucose?Math.round(r.glucose):"--",r.glucoseStatus);setCard("pulseCard","pulseValue","pulseStatus",r.pulse?Math.round(r.pulse):"--",r.pulseStatus);setCard("bpCard","bpValue","bpStatus",bp,bps);setCard("tempCard","tempValue","tempStatus",r.temperature?(((Number(r.temperature)-32)*5/9).toFixed(1)+"°C"):"--",r.temperatureStatus);setCard("bmiCard","bmiValue","bmiStatus",r.bmi?Number(r.bmi).toFixed(1):"--",r.bmiStatus);lastUpdated.textContent=r.dateTime?`Latest: ${r.dateTime}`:"Live Monitor"}
function makeTrend(){const rows=filteredRows(),v=vitalTrendSelect.value; if(trendChart)trendChart.destroy();trendChart=new Chart(trendChart=document.getElementById("trendChart"),{type:"line",data:{labels:rows.map(d=>d.dateTime.slice(5)),datasets:[{label:v,data:rows.map(d=>d[v]),borderColor:"#16a06b",backgroundColor:"rgba(22,160,107,.12)",fill:true,tension:.35,pointRadius:1}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{ticks:{maxTicksLimit:10}}},plugins:{legend:{display:false}}}})}
function makeStatus(){const rows=filteredRows(),sts=[];["glucoseStatus","pulseStatus","temperatureStatus","bmiStatus","systolicStatus","diastolicStatus","spo2Status","respirationStatus"].forEach(k=>rows.forEach(r=>sts.push(r[k]||"Unknown")));const c={};sts.forEach(s=>c[s]=(c[s]||0)+1);const labels=Object.keys(c);if(statusChart)statusChart.destroy();statusChart=new Chart(document.getElementById("statusChart"),{type:"doughnut",data:{labels,datasets:[{data:labels.map(l=>c[l]),backgroundColor:labels.map(statusColor),borderWidth:0}]},options:{cutout:"68%",plugins:{legend:{position:"bottom"}}}})}
function latestBaseRows(){let base=READINGS;if(doctorSelect.value!=="All")base=base.filter(d=>d.doctor===doctorSelect.value);if(dateSelect.value!=="Latest")base=base.filter(d=>d.date===dateSelect.value);base=base.filter(rowPassesSidebarFilters);return base}
function updateSnapshot(){const base=latestBaseRows(),names=[...new Set(base.map(d=>d.patientName))];const latest=names.map(p=>base.filter(d=>d.patientName===p).sort((a,b)=>new Date(a.dateTime)-new Date(b.dateTime)).pop()).filter(Boolean);snapshotTable.innerHTML=`<thead><tr><th>Patient</th><th>Doctor</th><th>Glucose</th><th>Pulse</th><th>BP</th><th>Temp</th><th>BMI</th><th>Updated</th></tr></thead><tbody>`+latest.map(r=>`<tr><td>${r.patientName}</td><td>${r.doctor}</td><td><span class="badge ${r.glucoseStatus}">${Math.round(r.glucose)} ${r.glucoseStatus}</span></td><td><span class="badge ${r.pulseStatus}">${Math.round(r.pulse)} ${r.pulseStatus}</span></td><td><span class="badge ${bpLevel(r)}">${Math.round(r.systolic)}/${Math.round(r.diastolic)} ${bpLevel(r)}</span></td><td><span class="badge ${r.temperatureStatus}">${Number(r.temperature).toFixed(1)} ${r.temperatureStatus}</span></td><td><span class="badge ${r.bmiStatus}">${Number(r.bmi).toFixed(1)} ${r.bmiStatus}</span></td><td>${r.dateTime}</td></tr>`).join("")+`</tbody>`}
function updateProfile(){const p=patientSelect.value,po=PATIENTS.find(x=>x.PatientName===p)||{},r=latestRow();const fields=[["Patient Name",p],["Patient ID",r.patientId||po.PatientID],["Doctor",r.doctor||po.Doctor],["Address",po.Address],["Primary Phone #",po["Primary Phone #"]],["Next Of Kin Name",po["Next Of Kin Name"]],["Next Of Kin Phone #",po["Next Of Kin Phone #"]],["DOB",po.DOB],["Primary Diagnosis",po["Primary Diagnosis"]],["Nearest Health Care Center",po["Nearest Health Care Center"]],["Insurance Provider",po["Insurance Provider"]],["Latest Reading",r.dateTime]];patientProfile.innerHTML=fields.map(([k,v])=>`<div><small>${k}</small><strong>${v||"--"}</strong></div>`).join("")}
function makeBPChart(){const rows=filteredRows();if(bpChart)bpChart.destroy();bpChart=new Chart(document.getElementById("bpChart"),{type:"line",data:{labels:rows.map(d=>d.dateTime.slice(5)),datasets:[{label:"Systolic",data:rows.map(d=>d.systolic),borderColor:"#e84c4f",tension:.35,pointRadius:1},{label:"Diastolic",data:rows.map(d=>d.diastolic),borderColor:"#0b1f70",tension:.35,pointRadius:1}]},options:{responsive:true,maintainAspectRatio:false,scales:{x:{ticks:{maxTicksLimit:10}}}}})}
function updateHistory(){const rows=filteredRows().slice(-48).reverse();historyTable.innerHTML=`<thead><tr><th>Date Time</th><th>Glucose</th><th>Pulse</th><th>BP</th><th>Temp</th><th>BMI</th><th>SpO2</th><th>Resp.</th></tr></thead><tbody>`+rows.map(r=>`<tr><td>${r.dateTime}</td><td>${Math.round(r.glucose)} ${r.glucoseStatus}</td><td>${Math.round(r.pulse)} ${r.pulseStatus}</td><td>${Math.round(r.systolic)}/${Math.round(r.diastolic)} ${bpLevel(r)}</td><td>${Number(r.temperature).toFixed(1)} ${r.temperatureStatus}</td><td>${Number(r.bmi).toFixed(1)} ${r.bmiStatus}</td><td>${Math.round(r.spo2)} ${r.spo2Status}</td><td>${Math.round(r.respiration)} ${r.respirationStatus}</td></tr>`).join("")+`</tbody>`}
function updateHeatmap(){const base=latestBaseRows(),date=dateSelect.value==="Latest"?[...new Set(READINGS.map(d=>d.date))].sort().pop():dateSelect.value,names=[...new Set(base.map(d=>d.patientName))].sort();let html=`<div class="heat-head">Patient</div>`+Array.from({length:24},(_,h)=>`<div class="heat-head">${String(h).padStart(2,"0")}</div>`).join("");names.forEach(p=>{html+=`<div class="heat-name">${p}</div>`;for(let h=0;h<24;h++){const r=base.find(d=>d.patientName===p&&d.date===date&&d.hour===h),worst=r?Math.max(score(r.glucoseStatus),score(r.pulseStatus),score(r.temperatureStatus),score(r.bmiStatus),score(bpLevel(r))):0,color=worst===3?"#e84c4f":worst===2?"#16a06b":worst===1?"#f4a340":"#87928f";html+=`<div class="heat-cell" style="background:${color}">${worst||"-"}</div>`}});heatmap.innerHTML=html}
function readingAlerts(row){if(!row)return[];const a=[];if(row.glucose>=180||row.glucoseStatus==="High")a.push({vital:"Glucose",value:`${Math.round(row.glucose)} mg/dL`,status:"High",threshold:"High if ≥ 180 mg/dL"});if(row.systolic>=130||row.diastolic>=80||bpLevel(row)==="High")a.push({vital:"Blood Pressure",value:`${Math.round(row.systolic)}/${Math.round(row.diastolic)} mmHg`,status:"High",threshold:"High if ≥ 130/80"});if(row.pulse>100||row.pulseStatus==="High")a.push({vital:"Pulse",value:`${Math.round(row.pulse)} bpm`,status:"High",threshold:"High if > 100 bpm"});if(row.temperature>=100.4||row.temperatureStatus==="High")a.push({vital:"Temperature",value:`${(((Number(row.temperature)-32)*5/9).toFixed(1))} °C`,status:"High",threshold:"High if ≥ 38 °C"});if(row.spo2<95||row.spo2Status==="Low")a.push({vital:"SpO2",value:`${Math.round(row.spo2)}%`,status:"Low",threshold:"Low if < 95%"});return a}
function makeMailto(row,al){const subject=encodeURIComponent(`AveTech Health Alert: ${al.vital} for ${row.patientName}`),body=encodeURIComponent(`AveTech Health Threshold Alert\n\nPatient: ${row.patientName}\nDoctor: ${row.doctor}\nReading Date/Time: ${row.dateTime}\n\nAlert Type: ${al.vital}\nReading: ${al.value}\nStatus: ${al.status}\nThreshold: ${al.threshold}\n\nPlease review the patient record and follow up as needed.`);return`mailto:?subject=${subject}&body=${body}`}
function updateThresholdAlerts(){const rows=filteredRows(),latest={};rows.forEach(r=>latest[r.patientName]=r);const items=[];Object.values(latest).forEach(row=>readingAlerts(row).forEach(al=>items.push({row,al})));alertCount.textContent=`${items.length} Alert${items.length===1?"":"s"}`;thresholdAlerts.innerHTML=items.length?items.slice(0,12).map(({row,al})=>`<div class="threshold-alert"><div><strong>${row.patientName}</strong><small>${row.doctor}</small></div><div><strong>${al.vital}</strong><small>${row.dateTime}</small></div><div><span class="alert-badge">${al.status}</span></div><div><strong>${al.value}</strong><small>${al.threshold}</small></div><a class="email-alert-btn" href="${makeMailto(row,al)}">Email</a></div>`).join(""):`<div class="no-alerts">No high-risk threshold alerts for the current selection.</div>`}
function valInfo(row,v){const m={glucose:["Glucose",row.glucose,row.glucoseStatus,50,250,"mg/dL"],pulse:["Pulse",row.pulse,row.pulseStatus,40,140,"bpm"],temperature:["Temperature",(((Number(row.temperature)-32)*5/9).toFixed(1)),row.temperatureStatus,35,41,"°C"],bmi:["Weight / BMI",row.bmi,row.bmiStatus,15,40,"BMI"],spo2:["SpO2",row.spo2,row.spo2Status,85,100,"%"],systolic:["Systolic",row.systolic,row.systolicStatus,80,180,"mmHg"],diastolic:["Diastolic",row.diastolic,row.diastolicStatus,50,120,"mmHg"]};return m[v]}
function rangeRow(label,val,st,min,max,unit){const pct=Math.max(0,Math.min(100,((Number(val)-min)/(max-min))*100));return`<div class="range-row"><div class="range-label"><span>${label}</span><span>${val} ${unit} • ${st}</span></div><div class="range-bar"><div class="range-pointer" style="left:${pct}%"></div></div><div class="range-ticks"><span>${min}</span><span>${Math.round((min+max)/2)}</span><span>${max}</span></div></div>`}
function renderVitalsDetail(){const rows=filteredRows(),r=rows[rows.length-1]||{};vitalsPatientTitle.textContent=`Patient: ${patientSelect.value}`;detailPatientLabel.textContent=`PATIENT: ${String(patientSelect.value).toUpperCase()}`;const labels={bp:"Blood Pressure",pulse:"Pulse",bmi:"Weight",spo2:"SpO2",glucose:"Glucose",temperature:"Temperature"};trackerTitle.textContent=labels[activeVitalTab];let ds=[],g="",s="";if(activeVitalTab==="bp"){const sy=valInfo(r,"systolic"),di=valInfo(r,"diastolic");s=`<div class="summary-chip"><small>Latest BP</small><strong>${Math.round(r.systolic||0)}/${Math.round(r.diastolic||0)}</strong></div><div class="summary-chip"><small>Status</small><strong>${bpLevel(r)}</strong></div><div class="summary-chip"><small>Last Updated</small><strong>${r.dateTime||"--"}</strong></div>`;g=rangeRow(...sy)+rangeRow(...di);ds=[{label:"Systolic",data:rows.map(x=>x.systolic),borderColor:"#e84c4f",tension:.35,pointRadius:1},{label:"Diastolic",data:rows.map(x=>x.diastolic),borderColor:"#0b1f70",tension:.35,pointRadius:1}]}else{const info=valInfo(r,activeVitalTab);s=`<div class="summary-chip"><small>Latest ${info[0]}</small><strong>${info[1]} ${info[5]}</strong></div><div class="summary-chip"><small>Status</small><strong>${info[2]}</strong></div><div class="summary-chip"><small>Last Updated</small><strong>${r.dateTime||"--"}</strong></div>`;g=rangeRow(...info);ds=[{label:info[0],data:rows.map(x=>x[activeVitalTab]),borderColor:"#0b1f70",backgroundColor:"rgba(11,31,112,.1)",fill:true,tension:.35,pointRadius:1}]}trackerSummary.innerHTML=s;trackerGaugeArea.innerHTML=g;trackerChartTitle.textContent=`${labels[activeVitalTab]} Hourly Trend`;if(vitalDetailChart)vitalDetailChart.destroy();vitalDetailChart=new Chart(document.getElementById("vitalDetailChart"),{type:"line",data:{labels:rows.map(x=>x.dateTime.slice(5)),datasets:ds},options:{responsive:true,maintainAspectRatio:false,scales:{x:{ticks:{maxTicksLimit:10}}}}});renderGrid(rows)}
function renderGrid(rows){const dates=[...new Set(rows.map(r=>r.date))].slice(-14);dailyReadingGrid.innerHTML=dates.map((date,i)=>{const r=rows.filter(x=>x.date===date).pop();if(!r)return"";let st,val;if(activeVitalTab==="bp"){st=bpLevel(r);val=`${Math.round(r.systolic)}/${Math.round(r.diastolic)}`}else{st=r[activeVitalTab+"Status"];val=activeVitalTab==="temperature"?(((Number(r[activeVitalTab])-32)*5/9).toFixed(1))+"°C":activeVitalTab==="bmi"?Number(r[activeVitalTab]).toFixed(1):Math.round(r[activeVitalTab])}return`<div class="reading-cell" style="background:${cellColor(st)}">${val}<small>${i+1}<br>${st}</small></div>`}).join("")}
function updateAll(){updateCards();makeTrend();makeStatus();updateSnapshot();updateProfile();makeBPChart();updateHistory();updateHeatmap();renderVitalsDetail();updateThresholdAlerts()}
document.querySelectorAll(".nav").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".nav").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.page).classList.add("active")}));
document.querySelectorAll(".vital-tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".vital-tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");activeVitalTab=btn.dataset.vital;renderVitalsDetail()}));
doctorSelect.addEventListener("change",()=>{refreshPatientOptions();updateAll()});bpLevelSelect.addEventListener("change",()=>{refreshPatientOptions();updateAll()});glucoseLevelSelect.addEventListener("change",()=>{refreshPatientOptions();updateAll()});patientSelect.addEventListener("change",updateAll);dateSelect.addEventListener("change",updateAll);vitalTrendSelect.addEventListener("change",updateAll);initFilters();updateAll();